name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      # get source code
      - name: checkout
        uses: actions/checkout@v3
      - name: pnpm 
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
      - name: build
        run: rm -rf node_modules && pnpm install && pnpm build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.